# Generated by Django 3.1.7 on 2021-03-05 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicicleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes', models.CharField(max_length=200, unique=True)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=5)),
                ('telefone', models.CharField(max_length=12)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicicleta.bicicleta')),
            ],
        ),
    ]
