# Generated by Django 3.1.7 on 2021-03-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomes', models.CharField(max_length=200, unique=True)),
                ('cep', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=19)),
            ],
        ),
    ]
